-- ============================================================================
-- API_DATA_PIPELINE — Enhanced Setup & Migration DDL
-- Supports: CURSOR + LINK pagination, configurable page size, records path,
-- dynamic filters, POST body, run summary, audit columns, indexes, views.
-- Idempotent: uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS throughout.
-- ============================================================================

-- ─── Database & Schemas ─────────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS API_DATA_PIPELINE;
CREATE SCHEMA IF NOT EXISTS API_DATA_PIPELINE.METADATA;
CREATE SCHEMA IF NOT EXISTS API_DATA_PIPELINE.RAW_LANDING;

USE SCHEMA API_DATA_PIPELINE.METADATA;

-- ─── INGESTION_CONFIGS (base table or migration) ────────────────────────────
CREATE TABLE IF NOT EXISTS API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS (
    API_ID              NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1,
    API_NAME            VARCHAR(16777216) NOT NULL,
    ENDPOINT_URL        VARCHAR(16777216),
    HTTP_METHOD         VARCHAR(16777216) DEFAULT 'GET',
    AUTH_TYPE           VARCHAR(16777216),
    API_KEY_HEADER      VARCHAR(16777216),
    SECRET_NAME         VARCHAR(16777216),
    TOKEN_URL           VARCHAR(16777216),
    PAGINATION_TYPE     VARCHAR(16777216),
    PAGE_PARAM          VARCHAR(16777216),
    START_INDEX         NUMBER(38,0) DEFAULT 1,
    MAX_RETRIES         NUMBER(38,0) DEFAULT 6,
    RETRY_DELAY_SEC     NUMBER(38,0) DEFAULT 15,
    TIMEOUT_SEC         NUMBER(38,0) DEFAULT 30,
    EXTRA_HEADERS_JSON  VARCHAR(16777216),
    LANDING_TABLE       VARCHAR(16777216),
    INCREMENTAL_FLAG    BOOLEAN DEFAULT FALSE,
    WATERMARK_PARAM     VARCHAR(16777216),
    WATERMARK_FIELD     VARCHAR(16777216),
    LAST_SYNC_VALUE     VARCHAR(16777216),
    ACTIVE_FLAG         BOOLEAN DEFAULT TRUE,
    CREATED_TS          TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (API_NAME),
    UNIQUE      (API_ID)
);

-- ─── Migration: add new columns to existing INGESTION_CONFIGS ────────────────
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS PAGE_SIZE           NUMBER DEFAULT 100;
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS LIMIT_PARAM         VARCHAR DEFAULT 'limit';
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS CURSOR_PARAM        VARCHAR;
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS CURSOR_PATH         VARCHAR;
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS HAS_MORE_PATH       VARCHAR;
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS TOTAL_PAGES_PATH    VARCHAR;
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS RECORDS_PATH        VARCHAR DEFAULT 'data';
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS REQUEST_BODY_JSON   VARCHAR;
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS FILTER_PARAMS       VARIANT;
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS MAX_PAGES           NUMBER DEFAULT 10000;
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS UPDATED_TS          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS CREATED_BY          VARCHAR DEFAULT CURRENT_USER();
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS UPDATED_BY          VARCHAR DEFAULT CURRENT_USER();

-- ─── INGESTION_RESPONSE_LOG (base or existing) ──────────────────────────────
CREATE TABLE IF NOT EXISTS API_DATA_PIPELINE.METADATA.INGESTION_RESPONSE_LOG (
    INSERT_DATETIME_UTC     TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    RUN_ID                  VARCHAR,
    API_ID                  NUMBER(38,0),
    API_NAME                VARCHAR(16777216),
    API_URL                 VARCHAR(16777216),
    STATUS_CODE             NUMBER(38,0),
    RESPONSE_TIME_SECONDS   FLOAT,
    ERROR_MESSAGE_TEXT      VARCHAR(16777216),
    RETRY_COUNT             NUMBER(38,0),
    ATTEMPT_NUMBER          NUMBER(38,0),
    IS_FINAL_ATTEMPT        BOOLEAN,
    PAGE_NUMBER             NUMBER(38,0)
);

ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_RESPONSE_LOG
    ADD COLUMN IF NOT EXISTS RUN_ID VARCHAR;

-- ─── INGESTION_RUN_SUMMARY (new — one row per ingestion run) ─────────────────
CREATE TABLE IF NOT EXISTS API_DATA_PIPELINE.METADATA.INGESTION_RUN_SUMMARY (
    RUN_ID              VARCHAR DEFAULT UUID_STRING(),
    API_NAME            VARCHAR,
    API_ID              NUMBER,
    RUN_START_UTC       TIMESTAMP_NTZ,
    RUN_END_UTC         TIMESTAMP_NTZ,
    PAGES_PROCESSED     NUMBER,
    TOTAL_CHUNKS        NUMBER,
    RECORDS_INGESTED    NUMBER,
    RECORDS_SKIPPED     NUMBER,
    STATUS              VARCHAR,
    WATERMARK_FROM      VARCHAR,
    WATERMARK_TO        VARCHAR,
    FINAL_PAGE_TYPE     VARCHAR,
    ERROR_MESSAGE       VARCHAR,
    INSERTED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ─── API_RAW_DATA (default landing table) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS API_DATA_PIPELINE.RAW_LANDING.API_RAW_DATA (
    INGEST_TS       TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    API_ID          NUMBER(38,0),
    API_NAME        VARCHAR(16777216),
    STATUS_CODE     NUMBER(38,0),
    PAYLOAD         VARIANT,
    PAYLOAD_HASH    VARCHAR(16777216),
    URL_ATTEMPTED   VARCHAR(16777216)
);

-- ─── Performance Indexes ─────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_response_log_api_time
    ON API_DATA_PIPELINE.METADATA.INGESTION_RESPONSE_LOG (API_NAME, INSERT_DATETIME_UTC);

CREATE INDEX IF NOT EXISTS idx_response_log_status
    ON API_DATA_PIPELINE.METADATA.INGESTION_RESPONSE_LOG (STATUS_CODE, INSERT_DATETIME_UTC);

CREATE INDEX IF NOT EXISTS idx_run_summary_api_start
    ON API_DATA_PIPELINE.METADATA.INGESTION_RUN_SUMMARY (API_NAME, RUN_START_UTC);

CREATE INDEX IF NOT EXISTS idx_raw_data_hash
    ON API_DATA_PIPELINE.RAW_LANDING.API_RAW_DATA (PAYLOAD_HASH);

CREATE INDEX IF NOT EXISTS idx_raw_data_api_ts
    ON API_DATA_PIPELINE.RAW_LANDING.API_RAW_DATA (API_NAME, INGEST_TS);

-- ─── Convenience Views ───────────────────────────────────────────────────────
CREATE OR REPLACE VIEW API_DATA_PIPELINE.METADATA.V_LATEST_RUNS AS
SELECT
    r.API_NAME,
    r.RUN_START_UTC,
    r.RUN_END_UTC,
    TIMESTAMPDIFF(SECOND, r.RUN_START_UTC, r.RUN_END_UTC) AS DURATION_SEC,
    r.PAGES_PROCESSED,
    r.RECORDS_INGESTED,
    r.RECORDS_SKIPPED,
    r.STATUS,
    r.WATERMARK_FROM,
    r.WATERMARK_TO,
    r.FINAL_PAGE_TYPE,
    r.ERROR_MESSAGE
FROM API_DATA_PIPELINE.METADATA.INGESTION_RUN_SUMMARY r
QUALIFY ROW_NUMBER() OVER (PARTITION BY r.API_NAME ORDER BY r.RUN_START_UTC DESC) = 1;

CREATE OR REPLACE VIEW API_DATA_PIPELINE.METADATA.V_ACTIVE_API_STATUS AS
SELECT
    c.API_NAME,
    c.ENDPOINT_URL,
    c.AUTH_TYPE,
    c.PAGINATION_TYPE,
    c.INCREMENTAL_FLAG,
    c.LAST_SYNC_VALUE,
    c.ACTIVE_FLAG,
    lr.STATUS        AS LAST_RUN_STATUS,
    lr.RUN_START_UTC AS LAST_RUN_TIME,
    lr.RECORDS_INGESTED AS LAST_RUN_RECORDS,
    lr.DURATION_SEC  AS LAST_RUN_DURATION_SEC
FROM API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS c
LEFT JOIN API_DATA_PIPELINE.METADATA.V_LATEST_RUNS lr
    ON c.API_NAME = lr.API_NAME
WHERE c.ACTIVE_FLAG = TRUE
ORDER BY c.API_NAME;

CREATE OR REPLACE VIEW API_DATA_PIPELINE.METADATA.V_ERROR_SUMMARY_7D AS
SELECT
    API_NAME,
    STATUS_CODE,
    COUNT(*) AS OCCURRENCES,
    COUNT(DISTINCT DATE_TRUNC('HOUR', INSERT_DATETIME_UTC)) AS HOURS_AFFECTED,
    MAX(INSERT_DATETIME_UTC) AS LAST_SEEN,
    ANY_VALUE(ERROR_MESSAGE_TEXT) AS SAMPLE_ERROR
FROM API_DATA_PIPELINE.METADATA.INGESTION_RESPONSE_LOG
WHERE INSERT_DATETIME_UTC >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
  AND (STATUS_CODE != 200 OR STATUS_CODE IS NULL)
GROUP BY API_NAME, STATUS_CODE
ORDER BY OCCURRENCES DESC;

-- ─── Backfill defaults for existing rows ─────────────────────────────────────
UPDATE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
SET
    PAGE_SIZE    = COALESCE(PAGE_SIZE, 100),
    LIMIT_PARAM  = COALESCE(LIMIT_PARAM, 'limit'),
    MAX_PAGES    = COALESCE(MAX_PAGES, 10000),
    RECORDS_PATH = COALESCE(RECORDS_PATH, 'data'),
    UPDATED_TS   = CURRENT_TIMESTAMP(),
    UPDATED_BY   = CURRENT_USER()
WHERE PAGE_SIZE IS NULL;

-- ── Export config table ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS API_DATA_PIPELINE.METADATA.EXPORT_CONFIGS (
    EXPORT_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
    API_NAME          VARCHAR NOT NULL,
    EXPORT_NAME       VARCHAR NOT NULL,
    ACTIVE_FLAG       BOOLEAN DEFAULT TRUE,
    STAGE_NAME        VARCHAR NOT NULL,
    EXPORT_PATH       VARCHAR NOT NULL,
    EXPORT_FORMAT     VARCHAR DEFAULT 'PARQUET',
    RECORDS_PATH      VARCHAR DEFAULT 'data',
    FLATTEN_FIELDS    VARIANT,
    LOAD_MODE         VARCHAR DEFAULT 'INCREMENTAL',
    PARTITION_BY_DATE BOOLEAN DEFAULT TRUE,
    PARTITION_FIELD   VARCHAR DEFAULT 'INGEST_TS',
    FILE_PREFIX       VARCHAR DEFAULT 'data',
    MAX_FILE_SIZE_MB  NUMBER DEFAULT 256,
    LAST_EXPORT_UTC   TIMESTAMP_NTZ,
    LAST_RUN_ID       VARCHAR,
    CREATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ── Export flag on ingestion configs ──────────────────────────
ALTER TABLE API_DATA_PIPELINE.METADATA.INGESTION_CONFIGS
    ADD COLUMN IF NOT EXISTS EXPORT_ENABLED BOOLEAN DEFAULT FALSE;
