SELECT * FROM INGESTION_CONFIGS;

SELECT * FROM RAW_LANDING.API_RAW_DATA;
SELECT * FROM RAW_LANDING.DEMO_CAT1;
select * from ingestion_response_log;


--- capture the response type

-- each retry capture the failure log

SHOW network rules;
show security integrations;
show secrets;

-- DROP NETWORK RULE API_DATA_PIPELINE.METADATA.NR_TWITCH_TEST;
-- DROP NETWORK RULE API_DATA_PIPELINE.METADATA.NR_JSONPLACEHOLDER_API;
-- DROP NETWORK RULE API_DATA_PIPELINE.METADATA.NR_DEMO_GAUNTLET;
-- DROP NETWORK RULE API_DATA_PIPELINE.METADATA.NR_TWITCH_API;


-- DROP SECRET API_DATA_PIPELINE.METADATA.SK_TWITCH_INT_TEST;
-- DROP SECURITY INTEGRATION SEC_INT_TWITCH_TEST;
-- DROP SECRET API_DATA_PIPELINE.METADATA.SK_TWITCH_OAUTH;
-- DROP SECURITY INTEGRATION API_DATA_PIPELINE.METADATA.TWITCH_OAUTH_INTEGRATION;
-- DROP SECURITY INTEGRATION API_DATA_PIPELINE.METADATA.SEC_INT_TWITCH;
-- DROP SECURITY INTEGRATION API_DATA_PIPELINE.METADATA.SEC_INT_POSTMAN_MOCK;



